<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="smoke test"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="6.747">
  <properties />
            <testcase name="verifyInvalidCredentials" time="4.669" classname="com.nopcommerce.demo.testSuite.LoginTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.No customer account found]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.No customer account found]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.nopcommerce.demo.testSuite.LoginTest.verifyInvalidCredentials(LoginTest.java:42)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verifyUserShouldNavigateToLoginPage" time="2.078" classname="com.nopcommerce.demo.testSuite.LoginTest" />
      
</testsuite>
